---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: imjoy-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /engine
        pathType: Prefix
        backend:
          service:
            name: imjoy-core-server
            port: 
              name: http
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-s3
            port:
              number: 9000      