---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: imjoy-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: imjoy-app-engine
            port: 
              name: http
      