apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: {{ .Values.minioStorageSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.minioStoragePath | quote }}