# define your environments and their k8s namespaces
namespaces:
  kube-public:
    protected: true
  kube-system:
    protected: true
  default:
    protected: true
  cert-manager:
    protected: true
  production:
    protected: true
    # limits:
    #   - type: Container
    #     default:
    #       cpu: "1000m"
    #       memory: "2048Mi"
    #     defaultRequest:
    #       cpu: "1000m"
    #       memory: "2048Mi"
    #   - type: Pod
    #     max:
    #       memory: "2048Mi"
  staging:
    protected: false
    labels:
      env: "staging"
    # quotas:
    #   limits.cpu: "10"
    #   limits.memory: "20Gi"
    #   pods: 25
    #   requests.cpu: "10"
    #   requests.memory: "30Gi"
    #   customQuotas:
    #     - name: "requests.nvidia.com/gpu"
    #       value: "2"