{{- if .Values.imjoyCoreServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: imjoy-core-server
  labels:
      app: imjoy-core-server
spec:
  selector:
    app: imjoy-core-server
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
{{- end }}