apiVersion: v1
kind: ConfigMap
metadata:
  name: imjoy-config-map
data:
  JWT_SECRET: F3eckV4uR5Q7KfNP3FqTVGuQA3wjeGAm
  ALLOW_ORIGINS: "*"
  AUTH0_AUDIENCE: https://imjoy.eu.auth0.com/api/v2/
  AUTH0_DOMAIN: imjoy.eu.auth0.com
  ADMINS: "oeway007@gmail.com"
