{{- if .Values.minioS3.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: minio-s3
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    app: minio-s3
{{- end }}