---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imjoy-app-engine
  labels:
    app: imjoy-app-engine
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: imjoy-app-engine
  template:
    metadata:
      labels:
        app: imjoy-app-engine
    spec:
      containers:
        - name: imjoy-app-engine
          image: imjoy-team/imjoy-app-engine
          imagePullPolicy: Never
          env:
            - name: AUTH0_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: AUTH0_DOMAIN
            - name: AUTH0_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: AUTH0_AUDIENCE
            - name: ALLOW_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: ALLOW_ORIGINS
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: JWT_SECRET
            - name: ADMINS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: ADMINS
            - name: ALLOW_LIST
              value: ""
            - name: VISIBILITY
              value: protected
            - name: LC_ALL
              value: C.UTF-8
            - name: LANG
              value: C.UTF-8
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          resources:
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 1
              memory: 512Mi
          readinessProbe:
            initialDelaySeconds: 30
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
