---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imjoy-core-server
  labels:
    app: imjoy-core-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: imjoy-core-server
  template:
    metadata:
      labels:
        app: imjoy-core-server
    spec:
      containers:
        - name: imjoy-core-server
          imagePullPolicy: IfNotPresent
          image: {{ .Values.global.dockerImage }}
          command: ["python3"]
          args: ["-m", "imjoy", "--serve", "--port=4000", "--host=0.0.0.0", "--allow-origin='*'"]
          env:
            - name: AUTH0_DOMAIN
              value: {{ .Values.auth0Domain | quote }}
            - name: AUTH0_AUDIENCE
              value: {{ .Values.auth0Audience | quote }}
            - name: ALLOW_ORIGINS
              value: {{ .Values.allowOrigins | quote }}
            - name: JWT_SECRET
              value: {{ .Values.jwtSecret | quote }}
            - name: ADMINS
              value: {{ .Values.admins | quote }}
            - name: ALLOW_LIST
              value: ""
            - name: VISIBILITY
              value: protected
            - name: LC_ALL
              value: C.UTF-8
            - name: LANG
              value: C.UTF-8
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          resources:
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 1
              memory: 512Mi
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /liveness
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
