apiVersion: v1
kind: Service
metadata:
  name: imjoy-app-engine
  labels:
      app: imjoy-app-engine
spec:
  selector:
    app: imjoy-app-engine
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
