{{- if .Values.minioS3.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: minio-s3
  labels:
      app: minio-s3
spec:
  type: {{ .Values.service.type }}
  selector:
    app: minio-s3
  ports:
    - port: 9000
      targetPort: http
      protocol: TCP
      name: http
{{- end }}
