name: "Create cluster using KinD"
on: [pull_request, push]

jobs:
  test-helm-chart:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: imjoy
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./controller
          load: true
          # only push the image if it's on master branch
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
          tags: |
            imjoy/imjoy-app-controller:latest
            imjoy/imjoy-app-controller:${{ github.sha }} 

      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.0"
      - name: Testing K8S
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}

      - name: Load docker image to k8s
        run: kind load docker-image imjoy/imjoy-app-controller:${{ github.sha }}
  
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.2
  
      - name: Test helm chart
        run: |
          helm install --wait --set engineImage=imjoy/imjoy-app-controller:${{ github.sha }} imjoy-app-engine ./charts/imjoy-app-engine/
          helm test imjoy-app-engine
          kubectl get pods --all-namespaces
